### PR TITLE
Redux in React Components

### PR DESCRIPTION
**Pull request by Adholah96**
# **In this project, I implented the following**

- [ ] Used Providers and configured created Store within it. 

- [ ] Created an initialState variable for the booksSlice

- [ ] Displayed books received from the slice, in a reusable component

- [ ] Dispatched actions using useDispatch

- [ ] Added  a <Button> component, which includes:

-   An event handler that adds a book to the books array (with attributes id, title and author)

- [ ] Added a <Button> component, which includes:

-   An event handler that removes a book from the books array (by id)

### CODE REVIEW

**Review by nahnahdev — COMMENTED** [review]
## Project Status: INVALIDATED :red_circle: 
Hi @Adholah96 , 

While you made a great effort in this project, I can't go ahead and review your code.


## Invalid Code Review Request

- This is because you have submitted a project, that doesn't have the [react&redux linters](https://github.com/microverseinc/linters-config/blob/master/react-redux) well set up in your project. So kindly include this in your project and ensure that there are [no linter errors](https://github.com/microverseinc/linters-config).:100: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Adholah96** [comment]
hello @NahnahAJ ,.. I have setup linters fine on my machine and its running and checking on my local machine.. It fails to check though when I create a PR 😊

**Comment by nahnahdev** [comment]
I see you've fixed it great job @Adholah96 :clap:

**Review by Zuhaib042 — APPROVED** [review]
Hi @Adholah96  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights
✅ Professional PR
✅ Professional Readme
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Adholah96** [comment]
thank you @Zuhaib042 😊

**Pull request merged**
